#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

set -euo pipefail

# This script collects all report artifacts and publishes them to gerrit-reports
# in a single commit to avoid race conditions.

REPORTS_TOKEN="${REPORTS_TOKEN:-}"
REPORTS_REPO="${REPORTS_REPO:-modeseven-lfit/gerrit-reports}"
ARTIFACTS_DIR="${ARTIFACTS_DIR:-./downloaded-reports}"

if [ -z "${REPORTS_TOKEN}" ]; then
  echo "::error::REPORTS_TOKEN environment variable not set; cannot publish reports."
  echo "::error::This should be a fine-grained PAT with Contents: Read and write permissions for ${REPORTS_REPO}"
  exit 1
fi

# Check if we have any reports to publish
if [ ! -d "${ARTIFACTS_DIR}" ] || [ -z "$(ls -A "${ARTIFACTS_DIR}" 2>/dev/null)" ]; then
  echo "::warning::No report artifacts found to publish."
  echo "This likely means all matrix jobs failed."
  exit 0
fi

echo "📦 Found report artifacts to publish:"
ls -la "${ARTIFACTS_DIR}/"

# Clone the target repository
workdir="$(mktemp -d)"
cd "${workdir}"

echo "Cloning target repository ${REPORTS_REPO}..."
git clone --depth 1 "https://${REPORTS_TOKEN}@github.com/${REPORTS_REPO}.git" repo
cd repo

git config user.name "lf-releng-reports-bot"
git config user.email "lf-releng+reports-bot@linuxfoundation.org"

# Process each report artifact
report_count=0
projects_updated=""

for artifact_dir in "${GITHUB_WORKSPACE}/${ARTIFACTS_DIR}"/reports-*; do
  if [ ! -d "$artifact_dir" ]; then
    continue
  fi

  # Extract project name from artifact directory name
  artifact_name=$(basename "$artifact_dir")
  project_name="${artifact_name#reports-}"

  echo "Processing report for: ${project_name}"

  # Check if report.html exists in the artifact
  report_file=$(find "$artifact_dir" -name "report.html" -type f | head -n 1)

  if [ -z "$report_file" ]; then
    echo "::warning::No report.html found for ${project_name}; skipping."
    continue
  fi

  # Generate slug from project name
  slug=$(echo "${project_name}" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')
  echo "  Slug: ${slug}"

  # Create target directory and copy report
  target_dir="projects/${slug}"
  mkdir -p "${target_dir}"
  cp "$report_file" "${target_dir}/report.html"

  # Create provenance file using jq
  jq -n \
    --arg project "${project_name}" \
    --arg slug "${slug}" \
    --arg run_id "${GITHUB_RUN_ID}" \
    --arg run_attempt "${GITHUB_RUN_ATTEMPT}" \
    --arg repo "${GITHUB_REPOSITORY}" \
    --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '{
      project: $project,
      slug: $slug,
      source_run_id: $run_id,
      source_run_attempt: $run_attempt,
      source_repo: $repo,
      generated_at_utc: $timestamp
    }' > "${target_dir}/.provenance.json"

  git add "${target_dir}/report.html" "${target_dir}/.provenance.json"
  report_count=$((report_count + 1))
  projects_updated="${projects_updated}- ${project_name} (${slug})\n"

  echo "  ✅ Prepared ${project_name} for commit"
done

if [ $report_count -eq 0 ]; then
  echo "::warning::No valid reports found to publish."
  exit 0
fi

# Check if there are changes to commit
if git diff --cached --quiet; then
  echo "No changes to commit; all reports are already up to date."
  exit 0
fi

# Commit all changes at once
echo "Committing changes for ${report_count} project(s)..."

# Create commit message in a file to handle multiline properly
cat > /tmp/commit-msg.txt <<EOF
chore: update ${report_count} project report(s) (run ${GITHUB_RUN_ID})

Projects updated:
$(echo -e "${projects_updated}")
Generated by: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
EOF

git commit -F /tmp/commit-msg.txt

# Push with retry logic
echo "Pushing changes to ${REPORTS_REPO}..."
for attempt in {1..3}; do
  echo "Push attempt ${attempt}/3..."

  if git push origin HEAD:main; then
    echo "✅ Successfully published ${report_count} report(s)"

    {
      echo "## 📤 Reports Published"
      echo ""
      echo "**Total reports published:** ${report_count}"
      echo ""
      echo "### Updated Projects:"
      echo -e "${projects_updated}"
      echo ""
      echo "**Repository:** ${REPORTS_REPO}"
    } >> "$GITHUB_STEP_SUMMARY"

    exit 0
  fi

  if [ "$attempt" -lt 3 ]; then
    echo "::warning::Push attempt ${attempt} failed; retrying..."
    sleep $((attempt * 2))
    git pull --rebase origin main || true
  fi
done

echo "::error::Failed to push reports after 3 attempts."
exit 1
